name: helio_tools
channels:
  - conda-forge
dependencies:
  - python=3.10
  # Standard Libraries
  - numpy # Numerical Linear Algebra
  - scipy # Scientific Computing
  - scikit-image
  - astropy
  - sunpy
  - conda-forge::aiapy
  - pandas # Data structure
  - scikit-learn # Machine Learning
  # PLOTTING LIBRARY
  - matplotlib # standard plotting library
  - seaborn # Stats viz library
  # Storage
  - conda-forge::netCDF4
  - conda-forge::zarr
  - conda-forge::gdal>=3.4.1,<=3.6.3
  # GUI
  - conda-forge::ipywidgets
  - ipykernel
  - conda-forge::tqdm
  - pip
  - pip:
      - toolz
      - einops
      - rastervision==0.21.3
      # formatting
      - black
      - pylint
      - isort
      - flake8
      - mypy
      - pytest
      - pre-commit
      # Notebook stuff
      - autoroot
      - pyprojroot
      - python-dotenv
      # logging
      - loguru
      # plotting
      - celluloid
      - corner
      - tabulate
      # experiment
      - hydra-core
      - hydra-zen
